apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: potok
type: Opaque
stringData:
  host: "postgres-service.potok.svc.cluster.local"
  username: "admin"
  password: "change-me-in-production"
  database: "adminservice"
